### ISSUE TITLE
Blog link is incorrect

### ISSUE THREAD

**Issue by pr0h4x0r2016** [pravj/geopattern#9]
I just figured I would point out that you have what looks like an older format in your blog link. Here is the new link:

https://pravj.github.io/blog/going-on-the-go-path/

I'll edit the markdown  and submit a pull request if you like, but I'm not at my desk right now.

**Comment by pravj** [comment]
Hi @pr0h4x0r2016,

Thanks for pointing this out.

It's amazing if you are willing to send a pull request.
I suggest replacing the protocol with *HTTP*, as some icons on the page are not loading on *HTTPS*.

**Comment by b4ux1t3** [comment]
I mistakenly opened the issue with a test account (pr0h4x0r2016). I have fixed the link and created a pull request.

**Comment by pravj** [comment]
Yo! That was quick. I just merged the pull request.
